### ISSUE TITLE
Broken source releases downloads for XZ and Zlib

### ISSUE THREAD

**Issue by nullgemm** [MIvanchev/static-wine32#12]
It seems the target Zlib file name was overlooked when updating the source URL. Also due to the recent XZ backdoor issue the upstream tarballs are no longer available. I fixed both of these lines [on my branch](https://github.com/nullgemm/static-wine32/commit/3458d243e7e543545c8634a1e1571499d18f8b30) and everything works fine with these changes. I can open a PR if you're OK with using the non-HTTPS debian source, but getting that over HTTP somehow feels a bit strange now :) I guess you know better than I do how you want to fix that so I'm just opening an issue.

**Comment by MIvanchev** [comment]
Please open a PR, yes, thank you. I've fixed the zlib issue already in the update I'm preparing for Wine 9.5 an 9.6 (will be pushing it tomorrow) but I forgot about XZ so yeah, let's have the HTTP for now... thanks for reminding me. Btw, the wine build will not be usable until tomorrow because I've updated the Wine repo already but not this repo due to rushing it and now there are some stuff I still need to finish patching. If you're experimenting however, glxgears and vkcube are usable to demonstrate the static Mesa. Thank you so much.

**Comment by MIvanchev** [comment]
@nullgemm I took https://git.tukaani.org/xz.git (tag v5.4.6) for xz, do you know if this version is good?

**Comment by nullgemm** [comment]
> @nullgemm I took https://git.tukaani.org/xz.git (tag v5.4.6) for xz, do you know if this version is good?

Yup, this is the latest stable version without compromised release tarballs.

Actually, as far as I understand reading the original [writeup](https://www.openwall.com/lists/oss-security/2024/03/29/4) by Andres Freund the backdoor is only present when building xz using the original release tarballs for tags v5.6.0 and v5.6.1 distributed and signed by the attackers known as "Jia Tan".

Because most distros base their packages on these specially-crafted release tarballs the backdoor started spreading, but unless I'm terribly mistaken building even the latest versions from source should be enough to avoid the main backdoor issue. You only need to make sure you do not use anything above v5.4.6 if you rely on the official release tarballs.

However we should all keep in mind various parts of the XZ source itself were of course slowly and cautiously weakened by the attackers in order the make the backdoor possible, so it would be nice to bump the version number soon when https://git.tukaani.org/xz.git is finally force-pushed with a clean git history - according to tukaani.org that will give us v5.8.0?
