### ISSUE TITLE
Documentation: is docker needed for this?

### ISSUE THREAD

**Issue by rubyFeedback** [MIvanchev/static-wine32#5]
Documentation: is docker needed for this?

I'd love to get back to wine; ever since the move to 64 bit I can no longer use it on my 64bit machine (it always whines about .wine' is a 32-bit installation, it cannot support 64-bit applications.' - I consider this a design mistake. It should never have such an error).

I don't really want to use docker though.

**Comment by MIvanchev** [comment]
Hey, currently it uses a lot of Docker, yeah, mainly because it makes it easier to build on remote servers which I also recommend to you (takes forever, more cores, excessive heat etc.). However with some help I could convert the Dockerfile to a shell script.

P.S.
Docker ist only needed to build it, it is **NOT** needed to run it.
